Repository Groww/ui-toolkit, pull requests merged in 2021-05, with the labels that each got.

#19 Old Component TS Migration (No API or design changes)
  package.json
  src/components/atoms/AnchorLink/index.tsx
  src/components/atoms/Dropdown/Dropdown.tsx
  src/components/atoms/Dropdown/DropdownContent.tsx
  src/components/atoms/Dropdown/DropdownTrigger.tsx
  src/components/atoms/Dropdown/dropDown.css
  src/components/atoms/Dropdown/index.ts
  src/components/atoms/IconStore/IconStore.tsx
  src/components/atoms/Popover/Popover.tsx
  src/components/atoms/Popover/index.ts
  src/components/atoms/Popover/popover.css
  src/components/atoms/Popup/Popup.tsx
  src/components/atoms/Popup/Rodal/Rodal.tsx
  src/components/atoms/Popup/Rodal/rodal.css
  src/components/atoms/Popup/index.ts
  src/components/atoms/Select/Select.tsx
  src/components/atoms/Select/index.ts
  src/components/atoms/Select/select.css
  src/components/atoms/index.ts
  stories/IconStore.stories.tsx
  stories/Popover.stories.tsx
  stories/Popup.stories.tsx
  stories/Select.stories.tsx
  stories/style.css
Labels: typescript only

#8 checkbox-group
  src/components/atoms/CheckBox/CheckBox.tsx
  src/components/atoms/CheckBox/index.ts
  src/components/molecules/CheckBoxGroup/CheckBoxGroup.tsx
  src/components/molecules/CheckBoxGroup/checkBoxGroup.css
  src/components/molecules/CheckBoxGroup/index.ts
  src/components/molecules/index.ts
  stories/CheckBoxGroup.stories.tsx
Labels: enhancement

#5 information-box
  src/components/atoms/InformationBoard/InformationBox.tsx
  src/components/atoms/InformationBoard/index.ts
  src/components/atoms/InformationBoard/informationBox.css
  src/components/atoms/index.ts
  stories/InformationBox.stories.tsx
Labels: enhancement

#3 Textarea
  src/components/atoms/TextArea/TextArea.tsx
  src/components/atoms/TextArea/index.ts
  src/components/atoms/TextArea/textArea.css
  src/components/atoms/index.ts
  stories/TextArea.stories.tsx
Labels: enhancement

#34 Atom/chip
  src/components/atoms/Chip/Chip.tsx
  src/components/atoms/Chip/chip.css
  src/components/atoms/Chip/index.ts
  src/components/atoms/index.ts
Labels: component
